### ISSUE TITLE
部分系统获取token失败

### ISSUE THREAD

**Issue by demossl** [chroblert/JCTokenUtil#1]
测试在Windows10 winserver2016  winserver2019可以获取token, win7 winserver2008 winserver2012获取失败

![1234](https://user-images.githubusercontent.com/29975349/120747280-54b3b700-c533-11eb-9180-0774f654e957.jpg)

**Comment by chroblert** [comment]
v1.1 已修复 
![image](https://user-images.githubusercontent.com/24365224/120879331-2ac2c900-c5f5-11eb-8ea3-a041bcdd5dc0.png)
